version: '3.8'
services:
  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres